global_defs {
    router_id AC_2
    enable_script_security
    script_user root
}

vrrp_script chk_ac_app {
    script "/etc/keepalived/check_app.sh"
    interval 2
    timeout 1
    fall 2
    rise 2
}

vrrp_instance VI_AC {
    state BACKUP
    interface TODO_INTERFACE
    virtual_router_id 51
    priority 100
    advert_int 1

    # Non-preempt avoids VIP moving back immediately when old master recovers.
    nopreempt

    unicast_src_ip TODO_AC2_IP
    unicast_peer {
        TODO_AC1_IP
    }

    authentication {
        auth_type PASS
        auth_pass acdhcp
    }

    virtual_ipaddress {
        TODO_VIP_CIDR dev TODO_INTERFACE
    }

    garp_master_delay 1
    garp_master_repeat 3
    garp_master_refresh 10
    garp_master_refresh_repeat 2

    track_script {
        chk_ac_app
    }

    notify_master "/etc/keepalived/notify.sh MASTER"
    notify_backup "/etc/keepalived/notify.sh BACKUP"
    notify_fault  "/etc/keepalived/notify.sh FAULT"
    notify_stop   "/etc/keepalived/notify.sh FAULT"
}
